name: CI Pipeline

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # TST-061: テスト分割実行とパラレル化の実装
      - name: Run tests in parallel (fast group)
        run: npm run test:parallel:fast
        env:
          NODE_OPTIONS: '--max-old-space-size=4096'
        timeout-minutes: 10

      - name: Run tests in parallel (medium group)
        run: npm run test:parallel:medium
        env:
          NODE_OPTIONS: '--max-old-space-size=4096'
        timeout-minutes: 15

      - name: Run tests in parallel (slow group)
        run: npm run test:parallel:slow
        env:
          NODE_OPTIONS: '--max-old-space-size=4096'
        timeout-minutes: 20

      - name: Run tests in parallel (core group)
        run: npm run test:parallel:core
        env:
          NODE_OPTIONS: '--max-old-space-size=4096'
        timeout-minutes: 20

      - name: Run tests in parallel (heavy group) 
        run: npm run test:parallel:heavy
        env:
          NODE_OPTIONS: '--max-old-space-size=6144'
        timeout-minutes: 25
        
      - name: Run ESM tests
        run: |
          mkdir -p data/test
          mkdir -p data/test-e2e
          mkdir -p .jest-cache
          npm run test:parallel:esm
        env:
          NODE_OPTIONS: '--experimental-vm-modules --max-old-space-size=4096'
        timeout-minutes: 20
        continue-on-error: true # ESMテストはまだ完全に安定していないため

      - name: Run smoke test
        run: npm run test:smoke
        continue-on-error: true # スモークテストは環境によって失敗する可能性があるため続行

      - name: Check for incomplete todo tasks in PRs
        if: github.event_name == 'pull_request'
        run: |
          if grep -q "- \[ \]" .todo/*.mdc; then
            echo "Error: There are uncompleted tasks in the todo files"
            grep "- \[ \]" .todo/*.mdc
            exit 1  # PRの場合は未完了タスクがあると失敗させる
          fi

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          retention-days: 30
