name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Run smoke test
      run: npm run backtest:smoke

    - name: Check todo files for uncompleted tasks
      run: |
        if grep -q "- \[ \]" .todo/*.mdc; then
          echo "Warning: There are uncompleted tasks in the todo files"
          grep "- \[ \]" .todo/*.mdc
          # Don't fail the build, just warn
        fi 